#version: '3.8'
#실행:  docker compose -f docker-compose.real.yml up --build
#서버 백그라운드 실행 docker compose -f docker-compose.real.yml up -d --build

services:
    
  web:
    build: .
    container_name: djangobnb_backend 
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --timeout 90     
    volumes:
      - .:/usr/src/djangobnb_backend/
      - media_volume:/usr/src/djangobnb_backend/media
    ports:
      - "8000:8000"      
    env_file:
      - ./.env
    environment:
      - PYTHONPATH=/usr/src/djangobnb_backend
    depends_on:
      - daphne


  #WebSocket 등 비동기 통신(ASGI)을  애플리케이션을 실행하는 서버 프로그램
  daphne:
    build: .
    command: daphne --bind 0.0.0.0 -p 8002 config.asgi:application
    ports:
      - 8002:8002
    volumes:
      - .:/usr/src/djangobnb_backend/
      - media_volume:/usr/src/djangobnb_backend/media
    environment:
      - PYTHONPATH=/usr/src/djangobnb_backend


volumes:
  media_volume: